### ISSUE TITLE
Instructions to build gem from release

### ISSUE THREAD

**Issue by daveaseeman** [copiousfreetime/crate#3]
Hi there,

Could you help me out by adding some quick instructions as to how to build this gem from a release?

When I downloaded the release I renamed `gemspec.rb` file to `crate.gemspec` but I am getting an error running `gem build crate.gemspec`.

Any help would be appreciated!

Thanks,
Dave

**Comment by copiousfreetime** [comment]
HI @daveaseeman crate is on the back burner for now, I haven't done any work on it for a number of years. As it stands crate was developed with ruby 1.8, and we are now on ruby 2.2. So I doubt any of what crate has in it would be valid at this time.

**Comment by daveaseeman** [comment]
No worries, thanks for the reply!

——

Dave
